//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFPatcher {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Configuration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Configuration() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDFPatcher.Configuration", typeof(Configuration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 书签文本 的本地化字符串。
        /// </summary>
        internal static string BookmarkText {
            get {
                return ResourceManager.GetString("BookmarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义工具栏按钮 的本地化字符串。
        /// </summary>
        internal static string CustomToolbarButtons {
            get {
                return ResourceManager.GetString("CustomToolbarButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档属性 的本地化字符串。
        /// </summary>
        internal static string DocInfo {
            get {
                return ResourceManager.GetString("DocInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正文文本 的本地化字符串。
        /// </summary>
        internal static string DocText {
            get {
                return ResourceManager.GetString("DocText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编码方式 的本地化字符串。
        /// </summary>
        internal static string Encodings {
            get {
                return ResourceManager.GetString("Encodings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出图片目录 的本地化字符串。
        /// </summary>
        internal static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息文件 的本地化字符串。
        /// </summary>
        internal static string InfoFiles {
            get {
                return ResourceManager.GetString("InfoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 减少占用内存 的本地化字符串。
        /// </summary>
        internal static string OptimalMemoryUsage {
            get {
                return ResourceManager.GetString("OptimalMemoryUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优化处理效率 的本地化字符串。
        /// </summary>
        internal static string OptimalSpeed {
            get {
                return ResourceManager.GetString("OptimalSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理选项 的本地化字符串。
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径 的本地化字符串。
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF读取方式 的本地化字符串。
        /// </summary>
        internal static string PdfLoadMode {
            get {
                return ResourceManager.GetString("PdfLoadMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF阅读器路径 的本地化字符串。
        /// </summary>
        internal static string PdfReaderPath {
            get {
                return ResourceManager.GetString("PdfReaderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 历史文件 的本地化字符串。
        /// </summary>
        internal static string RecentFiles {
            get {
                return ResourceManager.GetString("RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 替换文本 的本地化字符串。
        /// </summary>
        internal static string ReplaceItems {
            get {
                return ResourceManager.GetString("ReplaceItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置文件 的本地化字符串。
        /// </summary>
        internal static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存程序配置 的本地化字符串。
        /// </summary>
        internal static string SaveAppSettings {
            get {
                return ResourceManager.GetString("SaveAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查找文本 的本地化字符串。
        /// </summary>
        internal static string SearchItems {
            get {
                return ResourceManager.GetString("SearchItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入文件 的本地化字符串。
        /// </summary>
        internal static string SourceFiles {
            get {
                return ResourceManager.GetString("SourceFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标文件 的本地化字符串。
        /// </summary>
        internal static string TargetFiles {
            get {
                return ResourceManager.GetString("TargetFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
